### ISSUE TITLE
Position textarea and toneMat on top of eachother

### ISSUE THREAD

**Issue by Thomascountz** [Thomascountz/relay#36]
This will allow for the appearance of highlighting text inside of a `textarea`

```css
/* ./Editor/styles.css */
.editor {
  width: 100%;
  position: absolute;
  top: 150px;
  left: 25px;
  z-index: 2;
  padding: 0;
  background-color: transparent;
}
```

```css
/* ./ToneMat/styles.css */
.toneMat {
  width: 100%;
  position: absolute;
  top: 150px;
  left: 25px;
  z-index: 1;
}
